version: "3.8"

services:
  app:
    image: projeto-les
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mack
      MYSQL_DB: projeto-db

  mysql:
    image: mysql:5.7
    volumes:
      - projeto-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mack
      MYSQL_DATABASE: projeto-db

volumes:
  projeto-mysql-data:
